<?php

namespace AppBundle\Repository;

/**
 * InformationEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationEntryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInformationEntries() {
        return $this->getEntityManager()->findAll();
    }
}
